version: '3.3'

services:
  postgresql:
    image: docker.io/bitnami/postgresql:10
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_DATABASE=bitnami_airflow
      - POSTGRESQL_USERNAME=bn_airflow
      - POSTGRESQL_PASSWORD=bitnami1
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes

  airflow-scheduler:
    image: docker.io/bitnami/airflow-scheduler:2
    environment:
      - AIRFLOW_SECRET_KEY=LYs5mB40wBD5UoUOj_0b7sWpH4wlYzGDGx3XwHAfKgY=
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=LocalExecutor
      - AIRFLOW_WEBSERVER_HOST=airflow
    volumes:
      - ./dags:/opt/bitnami/airflow/dags
      - ./requirements.txt:/bitnami/python/requirements.txt

  airflow:
    image: docker.io/bitnami/airflow:2
    environment:
      - AIRFLOW_SECRET_KEY=LYs5mB40wBD5UoUOj_0b7sWpH4wlYzGDGx3XwHAfKgY=
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=LocalExecutor
      - AIRFLOW_PASSWORD=bitnami123
      - AIRFLOW_USERNAME=user
    ports:
      - '8080:8080'
    volumes:
      - ./dags:/opt/bitnami/airflow/dags
      - ./requirements.txt:/bitnami/python/requirements.txt

  livy-spark:
    image: john/livy-spark:0.3.0
    
    ports:
      - "8998:8998"
#    depends_on:
#      - spark-master
#      - spark-worker-a
#      - spark-worker-b
    environment:
#      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_DEPLOY_MODE=client
      - LOCAL_DIR_WHITELIST=/job

    volumes:
     - ../test_case:/job

volumes:
  postgresql_data:
    driver: local

